"""
FinCo AI - Alert Generator

Responsible for:
- Creating standardized financial alerts
- Generating human-readable explanations
- Attaching supporting evidence
- Generating initial recommendations
- Calculating alert metadata
- Producing audit-friendly alert payloads

This module intentionally does not persist alerts to the database.
Persistence belongs in alert_service.py / alert_repository.py.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import uuid4


# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------

@dataclass
class AlertEvidence:
    """
    Evidence supporting why an alert was generated.
    """

    metric: str
    value: Any
    threshold: Optional[Any] = None
    comparison: Optional[str] = None
    period: Optional[str] = None
    source: Optional[str] = None
    details: Optional[str] = None


@dataclass
class AlertRecommendation:
    """
    Initial recommendation attached to an alert.

    More sophisticated recommendations can later be generated by
    recommendation_service.py or the Recommendation Agent.
    """

    action: str
    priority: str = "MEDIUM"
    reason: Optional[str] = None
    expected_impact: Optional[str] = None


@dataclass
class GeneratedAlert:
    """
    Standard alert representation used by the FinCo AI alert pipeline.
    """

    alert_id: str
    company_id: str

    alert_type: str
    severity: str
    title: str
    message: str

    risk_score: float

    explanation: Optional[str] = None

    evidence: List[AlertEvidence] = field(default_factory=list)
    recommendations: List[AlertRecommendation] = field(default_factory=list)

    source: str = "financial_analysis"
    status: str = "OPEN"

    requires_human_review: bool = False

    created_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert the alert into a JSON-serializable dictionary.
        """

        result = asdict(self)

        result["created_at"] = self.created_at.isoformat()

        return result


# ---------------------------------------------------------------------------
# Alert Generator
# ---------------------------------------------------------------------------

class AlertGenerator:
    """
    Generates standardized alerts from financial risk events.

    Typical flow:

        Financial Analysis
                ↓
          Risk Scoring
                ↓
          Alert Generator
                ↓
          GeneratedAlert
                ↓
          Alert Service
                ↓
          Database / Notification
    """

    # Alert types
    FINANCIAL_PROFILE_DOWN = "FINANCIAL_PROFILE_DOWN"
    PREVIOUS_PERIOD_DECLINE = "PREVIOUS_PERIOD_DECLINE"
    SEVERE_LOSS_RISK = "SEVERE_LOSS_RISK"

    # Severity levels
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

    # Alert statuses
    OPEN = "OPEN"

    def __init__(
        self,
        default_source: str = "financial_analysis",
    ) -> None:
        self.default_source = default_source

    # -----------------------------------------------------------------------
    # Public API
    # -----------------------------------------------------------------------

    def generate_alert(
        self,
        company_id: str,
        alert_type: str,
        severity: str,
        risk_score: float,
        metrics: Optional[Dict[str, Any]] = None,
        evidence: Optional[List[AlertEvidence]] = None,
        recommendations: Optional[List[AlertRecommendation]] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> GeneratedAlert:
        """
        Generate a standardized alert.

        Parameters
        ----------
        company_id:
            Company associated with the alert.

        alert_type:
            Type of financial alert.

        severity:
            INFO / LOW / MEDIUM / HIGH / CRITICAL.

        risk_score:
            Risk score between 0 and 100.

        metrics:
            Financial metrics responsible for the alert.

        evidence:
            Supporting evidence.

        recommendations:
            Initial recommended actions.

        metadata:
            Additional contextual information.
        """

        metrics = metrics or {}
        evidence = evidence or []
        recommendations = recommendations or []
        metadata = metadata or {}

        normalized_risk = self._normalize_risk_score(risk_score)

        title = self._generate_title(
            alert_type=alert_type,
            severity=severity,
        )

        message = self._generate_message(
            alert_type=alert_type,
            metrics=metrics,
        )

        explanation = self.generate_explanation(
            alert_type=alert_type,
            severity=severity,
            risk_score=normalized_risk,
            metrics=metrics,
            evidence=evidence,
        )

        if not recommendations:
            recommendations = self.generate_recommendation(
                alert_type=alert_type,
                severity=severity,
                metrics=metrics,
            )

        requires_human_review = self._requires_human_review(
            severity=severity,
            risk_score=normalized_risk,
        )

        return GeneratedAlert(
            alert_id=self._generate_alert_id(),
            company_id=company_id,
            alert_type=alert_type,
            severity=severity,
            title=title,
            message=message,
            risk_score=normalized_risk,
            explanation=explanation,
            evidence=evidence,
            recommendations=recommendations,
            source=self.default_source,
            status=self.OPEN,
            requires_human_review=requires_human_review,
            metadata=metadata,
        )

    # -----------------------------------------------------------------------
    # Explanation
    # -----------------------------------------------------------------------

    def generate_explanation(
        self,
        alert_type: str,
        severity: str,
        risk_score: float,
        metrics: Dict[str, Any],
        evidence: List[AlertEvidence],
    ) -> str:
        """
        Generate a concise, deterministic explanation.

        This is intentionally rule-based.

        The LLM/Supervisor Agent can later enrich this explanation with:
        - RAG evidence
        - historical context
        - financial documents
        - forecasts
        - root-cause analysis
        """

        if alert_type == self.FINANCIAL_PROFILE_DOWN:
            return self._financial_profile_explanation(
                severity=severity,
                risk_score=risk_score,
                metrics=metrics,
            )

        if alert_type == self.PREVIOUS_PERIOD_DECLINE:
            return self._previous_period_explanation(
                severity=severity,
                risk_score=risk_score,
                metrics=metrics,
            )

        if alert_type == self.SEVERE_LOSS_RISK:
            return self._severe_loss_explanation(
                severity=severity,
                risk_score=risk_score,
                metrics=metrics,
            )

        return (
            f"A financial risk condition was detected with "
            f"a risk score of {risk_score:.1f}/100 and severity "
            f"{severity}."
        )

    # -----------------------------------------------------------------------
    # Recommendation
    # -----------------------------------------------------------------------

    def generate_recommendation(
        self,
        alert_type: str,
        severity: str,
        metrics: Dict[str, Any],
    ) -> List[AlertRecommendation]:
        """
        Generate initial rule-based recommendations.

        These recommendations are starting points.

        The Recommendation Agent can later produce context-aware
        recommendations using RAG, forecasting and what-if analysis.
        """

        if alert_type == self.FINANCIAL_PROFILE_DOWN:
            return [
                AlertRecommendation(
                    action="Review declining financial KPIs",
                    priority=self._recommendation_priority(severity),
                    reason="Multiple financial indicators are showing deterioration.",
                    expected_impact="Identify the primary drivers of financial weakness.",
                ),
                AlertRecommendation(
                    action="Perform root-cause analysis",
                    priority=self._recommendation_priority(severity),
                    reason="The decline should be investigated before corrective action.",
                    expected_impact="Improve decision quality and reduce recurring financial risk.",
                ),
            ]

        if alert_type == self.PREVIOUS_PERIOD_DECLINE:
            return [
                AlertRecommendation(
                    action="Compare current and previous periods",
                    priority=self._recommendation_priority(severity),
                    reason="Financial performance has declined compared with the previous period.",
                    expected_impact="Identify unfavorable changes in revenue, expenses or margins.",
                ),
                AlertRecommendation(
                    action="Review major expense and revenue drivers",
                    priority="MEDIUM",
                    reason="Driver-level analysis can explain the period-over-period decline.",
                    expected_impact="Identify controllable factors affecting profitability.",
                ),
            ]

        if alert_type == self.SEVERE_LOSS_RISK:
            return [
                AlertRecommendation(
                    action="Perform immediate financial risk review",
                    priority="CRITICAL",
                    reason="The projected loss risk is materially elevated.",
                    expected_impact="Reduce exposure to severe financial deterioration.",
                ),
                AlertRecommendation(
                    action="Run cash-flow and liquidity analysis",
                    priority="HIGH",
                    reason="Severe losses can create liquidity and business-continuity pressure.",
                    expected_impact="Identify potential funding or cash-flow problems early.",
                ),
                AlertRecommendation(
                    action="Run what-if recovery scenarios",
                    priority="HIGH",
                    reason="Scenario analysis can identify viable corrective actions.",
                    expected_impact="Compare possible recovery strategies before execution.",
                ),
            ]

        return [
            AlertRecommendation(
                action="Investigate the detected financial risk",
                priority=self._recommendation_priority(severity),
                reason="A financial anomaly or risk condition was detected.",
                expected_impact="Determine the appropriate corrective action.",
            )
        ]

    # -----------------------------------------------------------------------
    # Evidence
    # -----------------------------------------------------------------------

    def attach_evidence(
        self,
        alert: GeneratedAlert,
        evidence: List[AlertEvidence],
    ) -> GeneratedAlert:
        """
        Attach additional evidence to an existing alert.
        """

        alert.evidence.extend(evidence)

        return alert

    def create_evidence(
        self,
        metric: str,
        value: Any,
        threshold: Optional[Any] = None,
        comparison: Optional[str] = None,
        period: Optional[str] = None,
        source: Optional[str] = None,
        details: Optional[str] = None,
    ) -> AlertEvidence:
        """
        Convenience factory for creating evidence records.
        """

        return AlertEvidence(
            metric=metric,
            value=value,
            threshold=threshold,
            comparison=comparison,
            period=period,
            source=source,
            details=details,
        )

    # -----------------------------------------------------------------------
    # Titles
    # -----------------------------------------------------------------------

    def _generate_title(
        self,
        alert_type: str,
        severity: str,
    ) -> str:

        titles = {
            self.FINANCIAL_PROFILE_DOWN:
                "Financial Profile Deterioration Detected",

            self.PREVIOUS_PERIOD_DECLINE:
                "Financial Performance Declined",

            self.SEVERE_LOSS_RISK:
                "Severe Financial Loss Risk Detected",
        }

        title = titles.get(
            alert_type,
            "Financial Risk Alert",
        )

        return f"[{severity}] {title}"

    # -----------------------------------------------------------------------
    # Messages
    # -----------------------------------------------------------------------

    def _generate_message(
        self,
        alert_type: str,
        metrics: Dict[str, Any],
    ) -> str:

        if alert_type == self.FINANCIAL_PROFILE_DOWN:
            return (
                "The company's financial profile has deteriorated "
                "based on one or more monitored financial indicators."
            )

        if alert_type == self.PREVIOUS_PERIOD_DECLINE:
            return (
                "Current financial performance is below the "
                "previous reporting period."
            )

        if alert_type == self.SEVERE_LOSS_RISK:
            return (
                "The financial risk model indicates an elevated "
                "probability of severe financial loss."
            )

        return (
            "A financial risk condition has been detected "
            "and requires further investigation."
        )

    # -----------------------------------------------------------------------
    # Explanation Helpers
    # -----------------------------------------------------------------------

    def _financial_profile_explanation(
        self,
        severity: str,
        risk_score: float,
        metrics: Dict[str, Any],
    ) -> str:

        health_score = metrics.get("health_score")
        profitability = metrics.get("profitability")
        cash_flow = metrics.get("cash_flow")

        parts = [
            f"The financial profile is classified as {severity} risk.",
            f"The calculated risk score is {risk_score:.1f}/100.",
        ]

        if health_score is not None:
            parts.append(
                f"Financial health score: {health_score}."
            )

        if profitability is not None:
            parts.append(
                f"Profitability indicator: {profitability}."
            )

        if cash_flow is not None:
            parts.append(
                f"Cash-flow indicator: {cash_flow}."
            )

        return " ".join(parts)

    def _previous_period_explanation(
        self,
        severity: str,
        risk_score: float,
        metrics: Dict[str, Any],
    ) -> str:

        current_value = metrics.get("current_value")
        previous_value = metrics.get("previous_value")
        change_percent = metrics.get("change_percent")

        parts = [
            f"Performance has declined relative to the previous period.",
            f"Severity: {severity}.",
            f"Risk score: {risk_score:.1f}/100.",
        ]

        if current_value is not None:
            parts.append(
                f"Current value: {current_value}."
            )

        if previous_value is not None:
            parts.append(
                f"Previous value: {previous_value}."
            )

        if change_percent is not None:
            parts.append(
                f"Period-over-period change: {change_percent:.2f}%."
            )

        return " ".join(parts)

    def _severe_loss_explanation(
        self,
        severity: str,
        risk_score: float,
        metrics: Dict[str, Any],
    ) -> str:

        projected_loss = metrics.get("projected_loss")
        loss_probability = metrics.get("loss_probability")
        forecast_period = metrics.get("forecast_period")

        parts = [
            "The forecasting and risk models indicate a potential "
            "severe financial loss condition.",
            f"Severity: {severity}.",
            f"Risk score: {risk_score:.1f}/100.",
        ]

        if projected_loss is not None:
            parts.append(
                f"Projected loss: {projected_loss}."
            )

        if loss_probability is not None:
            parts.append(
                f"Estimated loss probability: {loss_probability}%."
            )

        if forecast_period is not None:
            parts.append(
                f"Forecast period: {forecast_period}."
            )

        return " ".join(parts)

    # -----------------------------------------------------------------------
    # Risk / Severity Helpers
    # -----------------------------------------------------------------------

    @staticmethod
    def _normalize_risk_score(
        risk_score: float,
    ) -> float:

        try:
            score = float(risk_score)
        except (TypeError, ValueError):
            score = 0.0

        return round(
            max(0.0, min(100.0, score)),
            2,
        )

    def _requires_human_review(
        self,
        severity: str,
        risk_score: float,
    ) -> bool:

        if severity == self.CRITICAL:
            return True

        if severity == self.HIGH and risk_score >= 75:
            return True

        return risk_score >= 90

    @staticmethod
    def _recommendation_priority(
        severity: str,
    ) -> str:

        if severity == "CRITICAL":
            return "CRITICAL"

        if severity == "HIGH":
            return "HIGH"

        if severity == "MEDIUM":
            return "MEDIUM"

        return "LOW"

    # -----------------------------------------------------------------------
    # ID Generation
    # -----------------------------------------------------------------------

    @staticmethod
    def _generate_alert_id() -> str:
        """
        Generate a unique application-level alert identifier.
        """

        return f"ALT-{uuid4().hex[:12].upper()}"


# ---------------------------------------------------------------------------
# Convenience Functions
# ---------------------------------------------------------------------------

def generate_alert(
    company_id: str,
    alert_type: str,
    severity: str,
    risk_score: float,
    metrics: Optional[Dict[str, Any]] = None,
    evidence: Optional[List[AlertEvidence]] = None,
    recommendations: Optional[List[AlertRecommendation]] = None,
    metadata: Optional[Dict[str, Any]] = None,
) -> GeneratedAlert:
    """
    Functional wrapper around AlertGenerator.

    Useful for simple service calls.
    """

    generator = AlertGenerator()

    return generator.generate_alert(
        company_id=company_id,
        alert_type=alert_type,
        severity=severity,
        risk_score=risk_score,
        metrics=metrics,
        evidence=evidence,
        recommendations=recommendations,
        metadata=metadata,
    )


__all__ = [
    "AlertEvidence",
    "AlertRecommendation",
    "GeneratedAlert",
    "AlertGenerator",
    "generate_alert",
]